# CIS 443 Exam 2, Part 2 Notebook
## 35 pts.
## Directions
1. Add your Grading ID below.
1. Answer each question in the cells provided.
1. When finished, save your work, close the Jupyter Lab file, and Shut Down Jupyter Lab. You will upload this Jupyter Notebook file as your submission to Question 1 in Exam 2, Part 2 in Blackboard.
1. Be sure to keep an unaltered version of this file just in case anything goes wrong in Blackboard.

__Grading ID__: P5279 (double click the cell in Jupyter to edit)

### Problem 1
Write a Python code fragment in the code cell below that reads a line of text, tokenizes the line using space characters as delimiters and outputs only those words beginning with the letter 'm'. Ignore the case of the words. (__5 pts.__)

In [4]:
text = input('Please enter a sentence: ')
text = text.upper()
tokens = text.split()
for word in tokens:
    if word.startswith('M'):
        print(word)

Please enter a sentence: who told you that you could call me after midnight
ME
MIDNIGHT


### Problem 2
Write a Python code fragment in the code cell below that uses a _list comprehension_ to map the range of integers from 1 through 20 (inclusive) onto each value's triple (that is the value times 3) but filtered to only operate on the odd numbers in the range (producing the triple of 1, the triple of 3, etc.). (__5 pts.__)

In [11]:
import numpy as np
numbers = np.arange(1,21)
new_num = [x*3 if x % 2 != 0 else x for x in numbers]
print(numbers)
print(new_num)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[3, 2, 9, 4, 15, 6, 21, 8, 27, 10, 33, 12, 39, 14, 45, 16, 51, 18, 57, 20]


### Problem 3
Write a Python code fragment in the code cell below that defines a function named `unique_words` that receives a list of words, then determines and displays in alphabetical order only the unique words. Treat uppercase and lowercase letters the same. The function should use a __set__ to get the unique words in the list. Test your function with several sentences. (__7 pts.__)

In [5]:
def unique_words(words):
    unique_set = set(words)
    ordered_list = sorted(list(unique_set), key=str.lower)
    print(ordered_list)
words = []
word = input('Please enter a list of words separated by a space: ')
words += word.split()
unique_words(words)

Please enter a list of words separated by a space: all of us Are Angry about Abbot
['Abbot', 'about', 'all', 'Angry', 'Are', 'of', 'us']


### Problem 4
Write a Python code fragment in the code cell below that defines a function named `calc_qual_pts` that accepts a letter grade (a string) as a parameter and returns the GPA quality points, as specified below, <u>using a dictionary to map each letter grade to its associated quality points</u>. If the grade is not one of the standard letter grades (A, B, C, D, F), return -1 to indicate this. Test the function with grades of "A", "C", and "X". (__7 pts.__)

| Grade | Quality Points |
| ----- | -------------- |
| A     | 4.0            |
| B     | 3.0            |
| C     | 2.0            |
| D     | 1.0            |
| F     | 0.0            |
| Otherwise | -1         |

In [12]:
def calc_qual_pts(grade):
    grade = grade.upper()
    grade_map = {'A':4.0, 'B':3.0, 'C':2.0, 'D':1.0, 'F':0.0}
    for letter,number in grade_map.items():
        if grade == letter:
            print(number)
            break
    if grade not in grade_map.keys():
        print('-1')

in_list = ['a','c','x']
for item in in_list:
    calc_qual_pts(item)

4.0
2.0
-1


### Problem 5
Write a Python code fragment in the code cell below that implements a function named `merge_to_dict` that will accept two parallel lists as parameters, the `key_list` and the `value_list`, and will return a dictionary of the associated key-value pairs. Write your own loop to accomplish this (don't just call `zip`!). You may assume that the lists are the same length. Test with a list of 3 names as keys and a list of 3 scores as the values. (__5 pts.__)

In [3]:
def merge_to_dict(key_list,value_list):
    merged = {}
    for key in key_list:
        for value in value_list:
            merged[key] = value
            value_list.remove(value)
            break
    print(merged)
            
key_list = ['George', 'Tim', 'Phil']
value_list = [65,82,73]
merge_to_dict(key_list,value_list)

{'George': 65, 'Tim': 82, 'Phil': 73}


### Problem 6
Use _arange_ to create a 2-by-2 _ndarray_ containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array creating a new _ndarray_ and printing its contents: (__2 pts. each__)
1. Cube every element of the array.
1. Add 7 to every element of the array.
1. Multiply every element of the array by 2.

In [11]:
import numpy as np

array1 = np.arange(4).reshape(2,2)
print('Original: \n',array1)

array2 = array1 ** 3
print('Answer 1:\n',array2)

array3 = array1 + 7
print('Answer 2:\n',array3)

array4 = array1 * 2
print('Answer 3:\n',array4)

Original: 
 [[0 1]
 [2 3]]
Answer 1:
 [[ 0  1]
 [ 8 27]]
Answer 2:
 [[ 7  8]
 [ 9 10]]
Answer 3:
 [[0 2]
 [4 6]]


### Problem 7 - Extra Credit
Use a regular expression to search through an input string (converted to all lower case letters when input) to locate all valid URLs within it. For this exercise, assume that a valid URL has the form:<br />
<span>http://</span>www.<i>domainname</i>.<i>extension</i><br />
where _domainname_ must consist of 1 or more word characters and _extension_ must be two or more letters. Use the regular expression function __findall__ to find all the URL substrings. (__5 pts. Extra Credit__)